repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace  # handle any whitespace of the end of line and the new line.
      - id: end-of-file-fixer # remove EOF of your whole files project.
        files: \.go$
      - id: check-yaml # fix yaml format file.
      - id: check-added-large-files # let you know which file has large file size.
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-mod-tidy # run go mod tidy -v.
      - id: go-fmt # automatically formats Go source code of your whole project.
      - id: go-imports # automatically update your Go import lines (add missing and remove unreferenced imports).
      - id: go-vet # examines Go source code and reports suspicious constructs.
      - id: go-cyclo # calculates cyclomatic complexities of functions in Go source code.
      - id: go-critic # a high quality linter for Go source code.
      - id: golangci-lint # run linter.
      - id: go-build # run go build command.
  - repo: local
    hooks:
      - id: go-unit-tests
        name: go-unit-tests
        description: run go tests with race detector
        entry: bash -c 'go test -race ./...'
        language: golang
        files: \.*$
        pass_filenames: false
      - id: typos
        name: typos
        description: check typo
        entry: bash -c 'typos'
        language: golang
        files: \.*$
        pass_filenames: false
#      - id: check-go-tests
#        name: Check Go Test Files
#        entry: ./check_go_tests.sh
#        language: script
#        files: \.go$
