// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.4
// source: protos/push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushPlayerOnlineState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OnlineState PlayerOnlineState `protobuf:"varint,1,opt,name=online_state,json=onlineState,proto3,enum=pb.PlayerOnlineState" json:"online_state,omitempty"`
}

func (x *PushPlayerOnlineState) Reset() {
	*x = PushPlayerOnlineState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushPlayerOnlineState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPlayerOnlineState) ProtoMessage() {}

func (x *PushPlayerOnlineState) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPlayerOnlineState.ProtoReflect.Descriptor instead.
func (*PushPlayerOnlineState) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushPlayerOnlineState) GetOnlineState() PlayerOnlineState {
	if x != nil {
		return x.OnlineState
	}
	return PlayerOnlineState_PLAYER_ONLINE_STATE_OFFLINE
}

type PushGroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupInfo *GroupInfo `protobuf:"bytes,1,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
}

func (x *PushGroupInfo) Reset() {
	*x = PushGroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushGroupInfo) ProtoMessage() {}

func (x *PushGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushGroupInfo.ProtoReflect.Descriptor instead.
func (*PushGroupInfo) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{1}
}

func (x *PushGroupInfo) GetGroupInfo() *GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

type PushInviteMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviterUid  string           `protobuf:"bytes,1,opt,name=inviter_uid,json=inviterUid,proto3" json:"inviter_uid,omitempty"`
	InviterName string           `protobuf:"bytes,2,opt,name=inviter_name,json=inviterName,proto3" json:"inviter_name,omitempty"`
	InviteeUid  string           `protobuf:"bytes,3,opt,name=invitee_uid,json=inviteeUid,proto3" json:"invitee_uid,omitempty"`
	Source      EnterGroupSource `protobuf:"varint,4,opt,name=source,proto3,enum=pb.EnterGroupSource" json:"source,omitempty"`
	GameMode    GameMode         `protobuf:"varint,5,opt,name=game_mode,json=gameMode,proto3,enum=pb.GameMode" json:"game_mode,omitempty"`
	ModeVersion int64            `protobuf:"varint,6,opt,name=mode_version,json=modeVersion,proto3" json:"mode_version,omitempty"`
}

func (x *PushInviteMsg) Reset() {
	*x = PushInviteMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushInviteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushInviteMsg) ProtoMessage() {}

func (x *PushInviteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushInviteMsg.ProtoReflect.Descriptor instead.
func (*PushInviteMsg) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{2}
}

func (x *PushInviteMsg) GetInviterUid() string {
	if x != nil {
		return x.InviterUid
	}
	return ""
}

func (x *PushInviteMsg) GetInviterName() string {
	if x != nil {
		return x.InviterName
	}
	return ""
}

func (x *PushInviteMsg) GetInviteeUid() string {
	if x != nil {
		return x.InviteeUid
	}
	return ""
}

func (x *PushInviteMsg) GetSource() EnterGroupSource {
	if x != nil {
		return x.Source
	}
	return EnterGroupSource_ENTER_GROUP_SOURCE_INVITATION
}

func (x *PushInviteMsg) GetGameMode() GameMode {
	if x != nil {
		return x.GameMode
	}
	return GameMode_GAME_MODE_TEST
}

func (x *PushInviteMsg) GetModeVersion() int64 {
	if x != nil {
		return x.ModeVersion
	}
	return 0
}

type PushAcceptInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteeUid  string `protobuf:"bytes,1,opt,name=invitee_uid,json=inviteeUid,proto3" json:"invitee_uid,omitempty"`
	InviteeName string `protobuf:"bytes,2,opt,name=invitee_name,json=inviteeName,proto3" json:"invitee_name,omitempty"`
}

func (x *PushAcceptInvite) Reset() {
	*x = PushAcceptInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushAcceptInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAcceptInvite) ProtoMessage() {}

func (x *PushAcceptInvite) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAcceptInvite.ProtoReflect.Descriptor instead.
func (*PushAcceptInvite) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{3}
}

func (x *PushAcceptInvite) GetInviteeUid() string {
	if x != nil {
		return x.InviteeUid
	}
	return ""
}

func (x *PushAcceptInvite) GetInviteeName() string {
	if x != nil {
		return x.InviteeName
	}
	return ""
}

type PushRefuseInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteeUid  string `protobuf:"bytes,1,opt,name=invitee_uid,json=inviteeUid,proto3" json:"invitee_uid,omitempty"`
	InviteeName string `protobuf:"bytes,2,opt,name=invitee_name,json=inviteeName,proto3" json:"invitee_name,omitempty"`
	RefuseMsg   string `protobuf:"bytes,3,opt,name=refuse_msg,json=refuseMsg,proto3" json:"refuse_msg,omitempty"`
}

func (x *PushRefuseInvite) Reset() {
	*x = PushRefuseInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushRefuseInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRefuseInvite) ProtoMessage() {}

func (x *PushRefuseInvite) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRefuseInvite.ProtoReflect.Descriptor instead.
func (*PushRefuseInvite) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{4}
}

func (x *PushRefuseInvite) GetInviteeUid() string {
	if x != nil {
		return x.InviteeUid
	}
	return ""
}

func (x *PushRefuseInvite) GetInviteeName() string {
	if x != nil {
		return x.InviteeName
	}
	return ""
}

func (x *PushRefuseInvite) GetRefuseMsg() string {
	if x != nil {
		return x.RefuseMsg
	}
	return ""
}

type PushGroupDissolve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *PushGroupDissolve) Reset() {
	*x = PushGroupDissolve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushGroupDissolve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushGroupDissolve) ProtoMessage() {}

func (x *PushGroupDissolve) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushGroupDissolve.ProtoReflect.Descriptor instead.
func (*PushGroupDissolve) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{5}
}

func (x *PushGroupDissolve) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type PushGroupState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupState GroupState `protobuf:"varint,1,opt,name=group_state,json=groupState,proto3,enum=pb.GroupState" json:"group_state,omitempty"`
}

func (x *PushGroupState) Reset() {
	*x = PushGroupState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushGroupState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushGroupState) ProtoMessage() {}

func (x *PushGroupState) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushGroupState.ProtoReflect.Descriptor instead.
func (*PushGroupState) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{6}
}

func (x *PushGroupState) GetGroupState() GroupState {
	if x != nil {
		return x.GroupState
	}
	return GroupState_GROUP_STATE_INVITE
}

type PushPlayerVoiceState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string           `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	VoiceState PlayerVoiceState `protobuf:"varint,2,opt,name=voice_state,json=voiceState,proto3,enum=pb.PlayerVoiceState" json:"voice_state,omitempty"`
}

func (x *PushPlayerVoiceState) Reset() {
	*x = PushPlayerVoiceState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushPlayerVoiceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPlayerVoiceState) ProtoMessage() {}

func (x *PushPlayerVoiceState) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPlayerVoiceState.ProtoReflect.Descriptor instead.
func (*PushPlayerVoiceState) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{7}
}

func (x *PushPlayerVoiceState) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PushPlayerVoiceState) GetVoiceState() PlayerVoiceState {
	if x != nil {
		return x.VoiceState
	}
	return PlayerVoiceState_PLAYER_VOICE_STATE_MUTE
}

type PushKick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *PushKick) Reset() {
	*x = PushKick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushKick) ProtoMessage() {}

func (x *PushKick) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushKick.ProtoReflect.Descriptor instead.
func (*PushKick) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{8}
}

func (x *PushKick) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type PushMatchInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchInfo *MatchInfo `protobuf:"bytes,1,opt,name=match_info,json=matchInfo,proto3" json:"match_info,omitempty"`
}

func (x *PushMatchInfo) Reset() {
	*x = PushMatchInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMatchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMatchInfo) ProtoMessage() {}

func (x *PushMatchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMatchInfo.ProtoReflect.Descriptor instead.
func (*PushMatchInfo) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{9}
}

func (x *PushMatchInfo) GetMatchInfo() *MatchInfo {
	if x != nil {
		return x.MatchInfo
	}
	return nil
}

type PushCancelMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CancelUid string `protobuf:"bytes,1,opt,name=cancel_uid,json=cancelUid,proto3" json:"cancel_uid,omitempty"`
}

func (x *PushCancelMatch) Reset() {
	*x = PushCancelMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushCancelMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCancelMatch) ProtoMessage() {}

func (x *PushCancelMatch) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCancelMatch.ProtoReflect.Descriptor instead.
func (*PushCancelMatch) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{10}
}

func (x *PushCancelMatch) GetCancelUid() string {
	if x != nil {
		return x.CancelUid
	}
	return ""
}

type PushReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReadyUid string `protobuf:"bytes,1,opt,name=ready_uid,json=readyUid,proto3" json:"ready_uid,omitempty"`
}

func (x *PushReady) Reset() {
	*x = PushReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReady) ProtoMessage() {}

func (x *PushReady) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReady.ProtoReflect.Descriptor instead.
func (*PushReady) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{11}
}

func (x *PushReady) GetReadyUid() string {
	if x != nil {
		return x.ReadyUid
	}
	return ""
}

type PushUnready struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnreadyUid string `protobuf:"bytes,1,opt,name=unready_uid,json=unreadyUid,proto3" json:"unready_uid,omitempty"`
}

func (x *PushUnready) Reset() {
	*x = PushUnready{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_push_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushUnready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUnready) ProtoMessage() {}

func (x *PushUnready) ProtoReflect() protoreflect.Message {
	mi := &file_protos_push_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUnready.ProtoReflect.Descriptor instead.
func (*PushUnready) Descriptor() ([]byte, []int) {
	return file_protos_push_proto_rawDescGZIP(), []int{12}
}

func (x *PushUnready) GetUnreadyUid() string {
	if x != nil {
		return x.UnreadyUid
	}
	return ""
}

var File_protos_push_proto protoreflect.FileDescriptor

var file_protos_push_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x51, 0x0a, 0x15, 0x50, 0x75, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x6f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x3d, 0x0a, 0x0d, 0x50, 0x75, 0x73, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x0d, 0x50, 0x75, 0x73, 0x68, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x4d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x5f,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x72, 0x55, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x65, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x55, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x6f,
	0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x56, 0x0a, 0x10, 0x50, 0x75, 0x73, 0x68, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x65, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x55, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x75, 0x0a,
	0x10, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x66, 0x75, 0x73, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x55,
	0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x66, 0x75, 0x73, 0x65, 0x5f,
	0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x75, 0x73,
	0x65, 0x4d, 0x73, 0x67, 0x22, 0x2e, 0x0a, 0x11, 0x50, 0x75, 0x73, 0x68, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x44, 0x69, 0x73, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x5f, 0x0a, 0x14, 0x50, 0x75, 0x73, 0x68, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x35, 0x0a, 0x0b, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x25, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68,
	0x4b, 0x69, 0x63, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22,
	0x3d, 0x0a, 0x0d, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x2c, 0x0a, 0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x30,
	0x0a, 0x0f, 0x50, 0x75, 0x73, 0x68, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x55, 0x69, 0x64,
	0x22, 0x28, 0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x79, 0x55, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x0b, 0x50, 0x75,
	0x73, 0x68, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x72,
	0x65, 0x61, 0x64, 0x79, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x79, 0x55, 0x69, 0x64, 0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_push_proto_rawDescOnce sync.Once
	file_protos_push_proto_rawDescData = file_protos_push_proto_rawDesc
)

func file_protos_push_proto_rawDescGZIP() []byte {
	file_protos_push_proto_rawDescOnce.Do(func() {
		file_protos_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_push_proto_rawDescData)
	})
	return file_protos_push_proto_rawDescData
}

var file_protos_push_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protos_push_proto_goTypes = []interface{}{
	(*PushPlayerOnlineState)(nil), // 0: pb.PushPlayerOnlineState
	(*PushGroupInfo)(nil),         // 1: pb.PushGroupInfo
	(*PushInviteMsg)(nil),         // 2: pb.PushInviteMsg
	(*PushAcceptInvite)(nil),      // 3: pb.PushAcceptInvite
	(*PushRefuseInvite)(nil),      // 4: pb.PushRefuseInvite
	(*PushGroupDissolve)(nil),     // 5: pb.PushGroupDissolve
	(*PushGroupState)(nil),        // 6: pb.PushGroupState
	(*PushPlayerVoiceState)(nil),  // 7: pb.PushPlayerVoiceState
	(*PushKick)(nil),              // 8: pb.PushKick
	(*PushMatchInfo)(nil),         // 9: pb.PushMatchInfo
	(*PushCancelMatch)(nil),       // 10: pb.PushCancelMatch
	(*PushReady)(nil),             // 11: pb.PushReady
	(*PushUnready)(nil),           // 12: pb.PushUnready
	(PlayerOnlineState)(0),        // 13: pb.PlayerOnlineState
	(*GroupInfo)(nil),             // 14: pb.GroupInfo
	(EnterGroupSource)(0),         // 15: pb.EnterGroupSource
	(GameMode)(0),                 // 16: pb.GameMode
	(GroupState)(0),               // 17: pb.GroupState
	(PlayerVoiceState)(0),         // 18: pb.PlayerVoiceState
	(*MatchInfo)(nil),             // 19: pb.MatchInfo
}
var file_protos_push_proto_depIdxs = []int32{
	13, // 0: pb.PushPlayerOnlineState.online_state:type_name -> pb.PlayerOnlineState
	14, // 1: pb.PushGroupInfo.group_info:type_name -> pb.GroupInfo
	15, // 2: pb.PushInviteMsg.source:type_name -> pb.EnterGroupSource
	16, // 3: pb.PushInviteMsg.game_mode:type_name -> pb.GameMode
	17, // 4: pb.PushGroupState.group_state:type_name -> pb.GroupState
	18, // 5: pb.PushPlayerVoiceState.voice_state:type_name -> pb.PlayerVoiceState
	19, // 6: pb.PushMatchInfo.match_info:type_name -> pb.MatchInfo
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protos_push_proto_init() }
func file_protos_push_proto_init() {
	if File_protos_push_proto != nil {
		return
	}
	file_protos_common_proto_init()
	file_protos_match_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushPlayerOnlineState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushGroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushInviteMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushAcceptInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushRefuseInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushGroupDissolve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushGroupState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushPlayerVoiceState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushKick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMatchInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushCancelMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_push_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushUnready); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_push_proto_goTypes,
		DependencyIndexes: file_protos_push_proto_depIdxs,
		MessageInfos:      file_protos_push_proto_msgTypes,
	}.Build()
	File_protos_push_proto = out.File
	file_protos_push_proto_rawDesc = nil
	file_protos_push_proto_goTypes = nil
	file_protos_push_proto_depIdxs = nil
}
