// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/match/accept_invite": {
            "post": {
                "description": "accept an invitation based on the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "accept an invitation",
                "parameters": [
                    {
                        "description": "Accept Invite Request Body",
                        "name": "AcceptInviteReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AcceptInviteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/cancel_match/{uid}": {
            "post": {
                "description": "cancel match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "cancel match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "player uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/change_role": {
            "post": {
                "description": "change a player's role based on the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "change a player's role",
                "parameters": [
                    {
                        "description": "Change Role Request Body",
                        "name": "ChangeRoleReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ChangeRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/create_group": {
            "post": {
                "description": "create a new group based on the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "create a new group",
                "parameters": [
                    {
                        "description": "Create Group Request Body",
                        "name": "CreateGroup",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pto.CreateGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/dissolve_group/{uid}": {
            "post": {
                "description": "dissolve a group based on the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "dissolve a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/enter_group": {
            "post": {
                "description": "enter a group based on the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "enter a group",
                "parameters": [
                    {
                        "description": "Enter Group Request Body",
                        "name": "EnterGroupReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.EnterGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/exit_group/{uid}": {
            "post": {
                "description": "exit a group based on the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "exit a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/invite": {
            "post": {
                "description": "invite a player based on the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "invite a player",
                "parameters": [
                    {
                        "description": "Invite Request Body",
                        "name": "InviteReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.InviteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/kick_player": {
            "post": {
                "description": "kick a player based on the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "kick a player",
                "parameters": [
                    {
                        "description": "Kick Player Request Body",
                        "name": "KickPlayerReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.KickPlayerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/refuse_invite": {
            "post": {
                "description": "refuse an invitation based on the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "refuse an invitation",
                "parameters": [
                    {
                        "description": "Refuse Invite Request Body",
                        "name": "RefuseInviteReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RefuseInviteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/set_nearby_join_group": {
            "post": {
                "description": "set whether group can be entered from nearby players list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "set nearby join group",
                "parameters": [
                    {
                        "description": "Set Nearby Join Group Request Body",
                        "name": "SetNearbyJoinGroupReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SetNearbyJoinGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/set_recent_join_group": {
            "post": {
                "description": "set whether group can be entered from recent players list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "set recent join group",
                "parameters": [
                    {
                        "description": "Set Recent Join Group Request Body",
                        "name": "SetRecentJoinGroupReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SetRecentJoinGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/set_voice_state": {
            "post": {
                "description": "set player voice state",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "set voice state",
                "parameters": [
                    {
                        "description": "Set Voice State Request Body",
                        "name": "SetVoiceStateReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SetVoiceStateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/match/start_match/{uid}": {
            "post": {
                "description": "start to match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match service"
                ],
                "summary": "start match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "player uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Concrete Error Msg",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AcceptInviteReq": {
            "type": "object",
            "required": [
                "group_id",
                "invitee_info",
                "inviter_uid"
            ],
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "invitee_info": {
                    "$ref": "#/definitions/pto.PlayerInfo"
                },
                "inviter_uid": {
                    "type": "string"
                }
            }
        },
        "api.ChangeRoleReq": {
            "type": "object",
            "required": [
                "captain_uid",
                "role",
                "target_uid"
            ],
            "properties": {
                "captain_uid": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/entry.GroupRole"
                },
                "target_uid": {
                    "type": "string"
                }
            }
        },
        "api.CreateGroupRsp": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer"
                }
            }
        },
        "api.EnterGroupReq": {
            "type": "object",
            "required": [
                "group_id",
                "player_info"
            ],
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "player_info": {
                    "$ref": "#/definitions/pto.EnterGroup"
                }
            }
        },
        "api.InviteReq": {
            "type": "object",
            "required": [
                "invitee_uid",
                "inviter_uid"
            ],
            "properties": {
                "invitee_uid": {
                    "type": "string"
                },
                "inviter_uid": {
                    "type": "string"
                }
            }
        },
        "api.KickPlayerReq": {
            "type": "object",
            "required": [
                "captain_uid",
                "kicked_uid"
            ],
            "properties": {
                "captain_uid": {
                    "type": "string"
                },
                "kicked_uid": {
                    "type": "string"
                }
            }
        },
        "api.RefuseInviteReq": {
            "type": "object",
            "required": [
                "group_id",
                "invitee_uid",
                "inviter_uid"
            ],
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "invitee_uid": {
                    "type": "string"
                },
                "inviter_uid": {
                    "type": "string"
                },
                "refuse_msg": {
                    "type": "string"
                }
            }
        },
        "api.SetNearbyJoinGroupReq": {
            "type": "object",
            "required": [
                "captain_uid"
            ],
            "properties": {
                "allow": {
                    "type": "boolean"
                },
                "captain_uid": {
                    "type": "string"
                }
            }
        },
        "api.SetRecentJoinGroupReq": {
            "type": "object",
            "required": [
                "captain_uid"
            ],
            "properties": {
                "allow": {
                    "type": "boolean"
                },
                "captain_uid": {
                    "type": "string"
                }
            }
        },
        "api.SetVoiceStateReq": {
            "type": "object",
            "required": [
                "uid"
            ],
            "properties": {
                "state": {
                    "maximum": 1,
                    "minimum": 0,
                    "allOf": [
                        {
                            "$ref": "#/definitions/entry.PlayerVoiceState"
                        }
                    ]
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "constant.GameMode": {
            "type": "integer",
            "enum": [
                -1,
                905
            ],
            "x-enum-varnames": [
                "GameModeTest",
                "GameModeGoatGame"
            ]
        },
        "entry.GroupRole": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "GroupRoleMember",
                "GroupRoleCaptain"
            ]
        },
        "entry.PlayerVoiceState": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "PlayerVoiceStateMute",
                "PlayerVoiceStateUnmute"
            ]
        },
        "pto.CreateGroup": {
            "type": "object",
            "required": [
                "game_mode",
                "mode_version",
                "uid"
            ],
            "properties": {
                "game_mode": {
                    "$ref": "#/definitions/constant.GameMode"
                },
                "glicko2_info": {
                    "$ref": "#/definitions/pto.Glicko2Info"
                },
                "mode_version": {
                    "type": "integer"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "pto.EnterGroup": {
            "type": "object",
            "required": [
                "game_mode",
                "mode_version",
                "uid"
            ],
            "properties": {
                "game_mode": {
                    "$ref": "#/definitions/constant.GameMode"
                },
                "glicko2_info": {
                    "$ref": "#/definitions/pto.Glicko2Info"
                },
                "mode_version": {
                    "type": "integer"
                },
                "source": {
                    "$ref": "#/definitions/pto.EnterGroupSourceType"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "pto.EnterGroupSourceType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "x-enum-comments": {
                "EnterGroupSourceTypeClanChannel": "from clan channel",
                "EnterGroupSourceTypeFriend": "from friend list",
                "EnterGroupSourceTypeNearby": "from recent list",
                "EnterGroupSourceTypeRecent": "from nearby list",
                "EnterGroupSourceTypeShare": "from share link",
                "EnterGroupSourceTypeWorldChannel": "from world channel"
            },
            "x-enum-varnames": [
                "EnterGroupSourceTypeNearby",
                "EnterGroupSourceTypeRecent",
                "EnterGroupSourceTypeFriend",
                "EnterGroupSourceTypeWorldChannel",
                "EnterGroupSourceTypeClanChannel",
                "EnterGroupSourceTypeShare"
            ]
        },
        "pto.Glicko2Info": {
            "type": "object",
            "properties": {
                "mmr": {
                    "type": "number"
                },
                "rank": {
                    "type": "integer"
                },
                "star": {
                    "type": "integer"
                },
                "start_match_sec": {
                    "type": "integer"
                }
            }
        },
        "pto.PlayerInfo": {
            "type": "object",
            "required": [
                "game_mode",
                "mode_version",
                "uid"
            ],
            "properties": {
                "game_mode": {
                    "$ref": "#/definitions/constant.GameMode"
                },
                "glicko2_info": {
                    "$ref": "#/definitions/pto.Glicko2Info"
                },
                "mode_version": {
                    "type": "integer"
                },
                "uid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
